GPT4:
  key1: f7d1587520404150834f123e39f18fd2
  key2: 16d90ea0765f46ddbd8b765ff6f92638
  end-point: https://oai-metlife-team009.openai.azure.com/
  model:
    deployment-or-name: gpt4-metlife-team09
    id: chatcmpl-95vAtJoHBnJK42kdNaYsXPRpjb2uN